# Copyright 2017 The Switch Authors. All rights reserved.
# Licensed under the Apache License, Version 2, which is in the LICENSE file.

import os
from pyomo.environ import *

"""

This module defines a simple Renewable Portfolio Standard (RPS) policy scheme
for the Switch-Pyomo model. In this scheme, each fuel is categorized as RPS-
elegible or not. All non-fuel energy sources are assumed to be RPS-elegible.
Dispatched electricity that is generated by RPS-elegible sources in each
period is summed up and must meet an energy goal, set as a required percentage
of all energy that is generated in that period.

This module assumes that the generators.core.no_commit module is being used.
An error will be raised if this module is loaded along the
generators.core.commit package.

TODO:
Allow the usage of the commit module.

"""

def define_components(mod):
    """
    
    f_rps_eligible[f in FUELS] is a binary parameter that flags each fuel as
    elegible for RPS accounting or not.
    
    RPS_ENERGY_SOURCES is a set enumerating all energy sources that contribute
    to RPS accounting. It is built by union of all fuels that are RPS elegible
    and the NON_FUEL_ENERGY_SOURCES set.
    
    RPS_PERIODS is a subset of PERIODS for which RPS goals are defined.
    
    rps_target[p in RPS_PERIODS] is the fraction of total generated energy in
    a period that has to be provided by RPS-elegible sources.
    
    RPSProjFuelPower[g, t in _FUEL_BASED_GEN_TPS] is an
    expression summarizing the power generated by RPS-elegible fuels in every
    fuel-based project. This cannot be simply taken to be equal to the
    dispatch level of the project, since a mix of RPS-elegible and unelegible
    fuels may be being consumed to produce that power. This expression is only
    valid when unit commitment is being ignored.
    
    RPSFuelEnergy[p] is an expression that sums all the energy produced using
    RPS-elegible fuels in fuel-based projects in a given period.
    
    RPSNonFuelEnergy[p] is an expression that sums all the energy produced
    using non-fuel sources in a given period.
    
    TotalGenerationInPeriod[p] is an expression that sums all the energy
    produced in a given period by all projects. This has to be calculated and
    cannot be taken to be equal to the total load in the period, because
    transmission losses could exist.
    
    RPS_Enforce_Target[p] is the constraint that forces energy produced by
    renewable sources to meet a fraction of the total energy produced in the
    period.
    
    """

    mod.PERIOD_ENERGY_MIN = Set(
    	dimen=2,
    	validate=lambda m, p, e: (
    		p in m.PERIODS and
    		e in m.ENERGY_SOURCES))

    mod.minimum_capacity = Param(
    	mod.PERIOD_ENERGY_MIN,
    	within=NonNegativeReals,
    	default=0)

    mod.Minimum_Capacity_Installed = Constraint(
    	mod.PERIOD_ENERGY_MIN,
    	rule=lambda m, p, e: (
    		sum(m.GenCapacity[g, p] for g in m.GENERATION_PROJECTS if m.gen_energy_source[g] == e) >= m.minimum_capacity[p, e]))

def load_inputs(mod, switch_data, inputs_dir):
    """
    The RPS target goals input file is mandatory, to discourage people from
    loading the module if it is not going to be used. It is not necessary to
    specify targets for all periods.
    
    Mandatory input files:
        rps_targets.tab
            PERIOD rps_target
    
    The optional parameter to define fuels as RPS eligible can be inputted
    in the following file:
        fuels.tab
            fuel  f_rps_eligible
    
    """

    switch_data.load_aug(
    	filename=os.path.join(inputs_dir, 'rps_capacity_min.tab'),
    	select=('Period', 'Energy_Source', 'Minimum_Capacity'),
    	index=(mod.PERIOD_ENERGY_MIN),
    	param=[mod.minimum_capacity])
